### ISSUE TITLE
Update user indicator design

### ISSUE THREAD

**Issue by ErwinSuwito** [TA-Software/RoundingPortal#30]
Update the user indicator design to the following

![image](https://user-images.githubusercontent.com/30384397/208666570-829ef4e1-64c8-447d-a564-6be7ba434981.png)

**Comment by neerooayusuf** [comment]
user indicator updated to the design from Dec 20, 2022
![image](https://user-images.githubusercontent.com/40438675/216291256-1beea12d-b30b-430c-b0c2-017b7cc3ab98.png)
